"""initial schema

Revision ID: 456274f7935d
Revises: 
Create Date: 2026-08-21 13:32:38.011625
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.base  # noqa: F401  (custom column types, e.g. Money)



revision: str = '456274f7935d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('rate_to_base', app.db.base.Money(precision=28, scale=8), nullable=False),
    sa.Column('decimals', sa.Integer(), server_default='2', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currencies_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('ref_code', sa.String(length=16), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('referral_source', sa.Enum('LINK', 'MANUAL', 'ADMIN', name='referralsource', native_enum=False, length=16), nullable=True),
    sa.Column('referred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discounts_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deals_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('balance', app.db.base.Money(precision=28, scale=8), server_default='0', nullable=False),
    sa.Column('total_earned', app.db.base.Money(precision=28, scale=8), server_default='0', nullable=False),
    sa.Column('total_paid_out', app.db.base.Money(precision=28, scale=8), server_default='0', nullable=False),
    sa.Column('is_blocked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_ref_code'), ['ref_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_referrer_id'), ['referrer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tg_id'), ['tg_id'], unique=True)

    op.create_table('pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency_id', sa.Integer(), nullable=False),
    sa.Column('to_currency_id', sa.Integer(), nullable=False),
    sa.Column('rate', app.db.base.Money(precision=28, scale=8), nullable=True),
    sa.Column('commission_percent', app.db.base.Money(precision=28, scale=8), nullable=False),
    sa.Column('min_amount', app.db.base.Money(precision=28, scale=8), nullable=True),
    sa.Column('max_amount', app.db.base.Money(precision=28, scale=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_currency_id'], ['currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_currency_id'], ['currencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency_id', 'to_currency_id', name='uq_pair')
    )
    with op.batch_alter_table('pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pairs_from_currency_id'), ['from_currency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pairs_to_currency_id'), ['to_currency_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=True),
    sa.Column('from_code', sa.String(length=16), nullable=False),
    sa.Column('to_code', sa.String(length=16), nullable=False),
    sa.Column('amount_from', app.db.base.Money(precision=28, scale=8), nullable=False),
    sa.Column('amount_to', app.db.base.Money(precision=28, scale=8), nullable=False),
    sa.Column('rate', app.db.base.Money(precision=28, scale=8), nullable=False),
    sa.Column('base_commission_percent', app.db.base.Money(precision=28, scale=8), nullable=False),
    sa.Column('discount_percent', app.db.base.Money(precision=28, scale=8), server_default='0', nullable=False),
    sa.Column('commission_percent', app.db.base.Money(precision=28, scale=8), nullable=False),
    sa.Column('discount_amount', app.db.base.Money(precision=28, scale=8), server_default='0', nullable=False),
    sa.Column('discount_applied', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('volume_base', app.db.base.Money(precision=28, scale=8), server_default='0', nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('bonus_amount', app.db.base.Money(precision=28, scale=8), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELLED', name='orderstatus', native_enum=False, length=16), server_default='pending', nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_referrer_id'), ['referrer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('REFERRAL_BONUS', 'PAYOUT', 'DISCOUNT', 'ADJUSTMENT', name='transactiontype', native_enum=False, length=24), nullable=False),
    sa.Column('amount', app.db.base.Money(precision=28, scale=8), nullable=False),
    sa.Column('balance_after', app.db.base.Money(precision=28, scale=8), server_default='0', nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('source_user_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_type'))

    op.drop_table('transactions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_referrer_id'))

    op.drop_table('orders')
    with op.batch_alter_table('pairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pairs_to_currency_id'))
        batch_op.drop_index(batch_op.f('ix_pairs_from_currency_id'))

    op.drop_table('pairs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tg_id'))
        batch_op.drop_index(batch_op.f('ix_users_referrer_id'))
        batch_op.drop_index(batch_op.f('ix_users_ref_code'))

    op.drop_table('users')
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currencies_code'))

    op.drop_table('currencies')
    # ### end Alembic commands ###
