"""drop commission, track bonuses and admin cards

Revision ID: d7e1db1ff6c6
Revises: 456274f7935d
Create Date: 2026-08-21 15:50:12.175706
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.base  # noqa: F401  (custom column types, e.g. Money)


revision: str = "d7e1db1ff6c6"
down_revision: str | None = "456274f7935d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("to_decimals", sa.Integer(), server_default="2", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "bonus_spent",
                app.db.base.Money(precision=28, scale=8),
                server_default="0",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "bonus_spent_to",
                app.db.base.Money(precision=28, scale=8),
                server_default="0",
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("admin_messages", sa.Text(), nullable=True))
        batch_op.drop_column("commission_percent")
        batch_op.drop_column("base_commission_percent")

    with op.batch_alter_table("pairs", schema=None) as batch_op:
        batch_op.drop_column("commission_percent")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pairs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("commission_percent", sa.VARCHAR(length=48), nullable=False))

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("base_commission_percent", sa.VARCHAR(length=48), nullable=False)
        )
        batch_op.add_column(sa.Column("commission_percent", sa.VARCHAR(length=48), nullable=False))
        batch_op.drop_column("admin_messages")
        batch_op.drop_column("bonus_spent_to")
        batch_op.drop_column("bonus_spent")
        batch_op.drop_column("to_decimals")

    # ### end Alembic commands ###
